[package]
name = "subxtpy"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21.1", features = ["extension-module"] }
subxt = "0.35.2"
subxt-signer = "0.35.2"

[dev-dependencies]
maturin = "0.12"
