[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
authors = [{ name = "Philomath Ingeniare", email = "philoniare@gmail.com" }]
license = "Apache-2.0"
readme = "README.md"
name = "subxtpy"
version = "0.1.0"
