[package]
name = "py_subxt_wrapper"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.15", features = ["extension-module"] }
subxt = "0.35.2"

[dev-dependencies]
maturin = "0.12"
